USE [master]
GO

/****** Object:  Database [newdb]    Script Date: 11/15/2021 8:52:41 AM ******/
CREATE DATABASE [newdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'newdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\newdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'newdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\newdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [newdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [newdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [newdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [newdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [newdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [newdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [newdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [newdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [newdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [newdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [newdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [newdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [newdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [newdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [newdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [newdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [newdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [newdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [newdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [newdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [newdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [newdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [newdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [newdb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [newdb] SET  MULTI_USER 
GO

ALTER DATABASE [newdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [newdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [newdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [newdb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [newdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [newdb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [newdb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [newdb] SET  READ_WRITE 
GO



USE [newdb]
GO

/****** Object:  Table [dbo].[regtbl]    Script Date: 11/14/2021 6:30:17 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON



GO
CREATE TABLE [dbo].[regtbl] (
    [Id]         INT           NOT NULL,
    [FirstName]  NVARCHAR(50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [LastName]   NVARCHAR(50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Contact]    NVARCHAR(50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Gender]     NCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Address]    NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [date_day]   INT           NULL,
    [date_month] NVARCHAR(50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [date_year]  INT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
